name: 'Branch Database Action'
author: DevOps
description: Create, Recreate or Delete a branch database

inputs:
  branch_action:
    description: 'Create, Recreate or Delete a branch database. Default is Create.'
    required: false
    default: 'Create'
  database_name:
    description: 'Database name'
    required: true
  source_database_name:
    description: 'Source database name. Default is patriot_pay'
    required: false
    default: 'patriot_pay'
  github_actor:
    description: 'GitHub actor property'
    required: true
  aws_access_key:
    description: 'AWS Access Key (Required if no aws-actions/configure-aws-credentials)'
    required: true
  aws_secret_key:
    description: 'AWS Secret Key (Required if no aws-actions/configure-aws-credentials)'
    required: true
  aws_region:
    description: 'AWS Region'
    required: false
    default: 'us-east-1'
    
runs:
  using: 'composite'
  steps:
    - if: |
        inputs.database_name == '' ||
        inputs.github_actor == '' ||
        inputs.database_name == 'master' || 
        inputs.database_name == 'main' ||
        (inputs.branch_action != 'Delete' && inputs.source_database_name == '')
      shell: bash
      run: |
        echo "Inputs validation failed."
        exit 1

    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Authenticate with DEV
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key }}
        aws-secret-access-key: ${{ inputs.aws_secret_key }}
        aws-region: ${{ inputs.aws_region }}

    - env:
        DATABASE: ${{ inputs.database_name }}
        USERNAME: ${{ inputs.github_actor }}
        SOURCE_DB: ${{ inputs.source_database_name }}
        ACTION: ${{ inputs.branch_action }}
      shell: bash
      run: bash ${{ github.action_path }}/script.sh

